/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PossibleReordering */

#ifndef _Included_PossibleReordering
#define _Included_PossibleReordering
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
